### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by quarterturn** [SenZmaKi/Senpwai#69]
Since 12/3 it has a json parsing issue with what gogoanime seems to be returning:
```
Traceback (most recent call last):
  File "/home/anon/.conda/envs/senpwai/lib/python3.11/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anon/.conda/envs/senpwai/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anon/.conda/envs/senpwai/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anon/.conda/envs/senpwai/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anon/.conda/envs/senpwai/bin/senpcli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/anon/.conda/envs/senpwai/lib/python3.11/site-packages/senpwai/senpcli/main.py", line 910, in main
    anime_details = get_anime_details(parsed)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anon/.conda/envs/senpwai/lib/python3.11/site-packages/senpwai/senpcli/main.py", line 761, in get_anime_details
    anime = search(parsed.title, parsed.site)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anon/.conda/envs/senpwai/lib/python3.11/site-packages/senpwai/senpcli/main.py", line 274, in search
    else [Anime(*r, None) for r in gogo.search(title)]
                                   ^^^^^^^^^^^^^^^^^^
  File "/home/anon/.conda/envs/senpwai/lib/python3.11/site-packages/senpwai/scrapers/gogo/main.py", line 37, in search
    content = response.json()["content"]
              ^^^^^^^^^^^^^^^
  File "/home/anon/.conda/envs/senpwai/lib/python3.11/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
It was working fine 12/3.

**Comment by quarterturn** [comment]
Version 2.1.14 btw
