### ISSUE TITLE
Installation error: subprocess-exited-with-error 

### ISSUE THREAD

**Issue by hillz2** [SenZmaKi/Senpwai#72]
I'm running alpine linux on docker, this is what I did:
```
python -m venv .venv 
source .venv/bin/activate
python -m pip install senpwai
```
and this is the error:
```
Collecting pyqt6<7.0.0,>=6.6.1 (from senpwai)
  Using cached PyQt6-6.8.0.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  _ Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  _─> [25 lines of output]
      Traceback (most recent call last):
        File "/root/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-19mgjqx2/overlay/lib/python3.12/site-packages/sipbuild/api.py", line 28, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-19mgjqx2/overlay/lib/python3.12/site-packages/sipbuild/abstract_project.py", line 74, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-19mgjqx2/overlay/lib/python3.12/site-packages/sipbuild/project.py", line 608, in setup
          self.apply_user_defaults(tool)
        File "/tmp/pip-install-m038m5ax/pyqt6_529fca38867d44a6912b93032f4e0385/project.py", line 66, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-19mgjqx2/overlay/lib/python3.12/site-packages/pyqtbuild/project.py", line 51, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-19mgjqx2/overlay/lib/python3.12/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-19mgjqx2/overlay/lib/python3.12/site-packages/pyqtbuild/builder.py", line 49, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

_ Encountered error while generating package metadata.
_─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```
How should I install it correctly ?

**Comment by SenZmaKi** [comment]
It works perfectly on ubuntu. Honestly this is probably something to do with alpine linux cause qt requires some native os stuff that I don't think alpine linux comes with. If you don't mind me asking why are you dockerizing it and do you have to use alpine linux specifically?

**Comment by hillz2** [comment]
Yes, works fine on Ubuntu, alphine is lightweight and I just love docker, it's fine I'll just use Ubuntu
